version: 2

macros:
  - name: get_days_from_hours
    description: Convert hours to days.
    arguments:
      - name: hours
        description: Number of hours.
        type: integer
  
  - name: format_transaction_type
    description: Define new column based on condicional statments on transaction_type.
    arguments:
      - name: transactions.transaction_type
        description: transation status.
        type: string
