version: 2

macros:
  - name: get_days_from_hours
    description: Convert hours to days.
    arguments:
      - name: hours
        description: Number of hours.
        type: integer
  - name: format_transaction_type
    description: Mapping convertions between transaction types from transcript seed.
    arguments:
      - name: transaction_type
        description: Type of event. Can be offer received, offer viewed, transaction, or offer completed.
        type: text
