version: 2

macros:
  - name: get_days_from_hours
    description: Convert hours to days.
    arguments:
      - name: hours
        description: Number of hours.
        type: integer
  - name: format_transation_type
    description: convert transaction type by list
    arguments:
      - name: column
        description: column to be used
        type: text
